[build-system]
requires = [
    "setuptools >= 69,< 84",
    "setuptools-scm >= 8,< 11",
    "Cython ~= 3.0",
    "wheel ~= 0.43",
]

# configure with setup.py
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "horseradish",
    "horseradish.core_commands",
    "horseradish.game_modes",
    "horseradish.scripts",
    "horseradish.utils",

    "pyspades",

    "horseradish.config",
    "horseradish.config.game_modes",
    "horseradish.config.scripts",
    "horseradish.config.maps",
    "horseradish.web",
]

[tool.setuptools.package-data]
horseradish = ["web/templates/*.html"]

[tool.setuptools_scm]
version_file = "horseradish/_version.py"

[tool.tox]
legacy_tox_ini = """
[tox]
requires =
    tox>=4

env_list = py{38,39,310,311}

[testenv]
package = editable
extras = dev, from, ssh
description = run unit tests
deps =
    pytest>=8
    pytest-sugar
commands =
    pytest tests/
"""

[tool.coverage.run]
branch = true
source = [
    "horseradish",
    "pyspades",
]

omit = [
    "horseradish/scripts/*",
    "horseradish/game_modes/*",
]

plugins = [
    "Cython.Coverage",
]

[project]
name = "horseradish"
description = "Open-Source server implementation for Ace of Spades"
readme = "README.rst"
license = "GPL-3.0-or-later"
dynamic = ["version"]

authors = [
    { name = "Mathias Kærlev (matpow2)", email = "matpow2@gmail.com" },
    { name = "Nate Shoffner", email = "nate.shoffner@gmail.com" },
    { name = "NotAFile", email = "notafile@gmail.com" },
    { name = "pyspades, PySnip and piqueserver contributors" },
]

keywords = [
    "ace of spades",
    "aos",
    "server",
    "pyspades",
    "pysnip",
    "piqueserver",
]

classifiers = [
    "Intended Audience :: System Administrators",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Unix",
    "Operating System :: Microsoft :: Windows",
    "Environment :: Console",
    "Programming Language :: Python",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3",
    "Framework :: AsyncIO",
    "Topic :: Games/Entertainment",
    "Topic :: Games/Entertainment :: First Person Shooters",
]

requires-python = ">= 3.10"
dependencies = [
    'tomli >= 1.1.0; python_version < "3.11"',
    "packaging >= 19.0",

    # windows specific
    'pypiwin32; platform_system=="Windows"',
]

[project.scripts]
horseradish = "horseradish.run:main"

[project.optional-dependencies]
# '/from' command
from = [
    "geoip2 >= 2.9, < 6.0",
]

# ssh script
ssh = [
    "asyncssh",
]

# status server
web = [
    "Jinja2 >= 3.0.0, <4",
    "Pillow >= 5.1.0, < 13",
    "aiohttp >= 3.3.0, < 3.15.0",
]

# development dependencies
dev = [
    "Cython",
    "flake8",
    "coveralls",
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "Sphinx",
    "tox",
    "sphinx_rtd_theme",
    "asyncssh",
    "Jinja2 >= 3.0.0, <4",
    "Pillow >= 5.1.0, < 13",
    "aiohttp >= 3.3.0, < 3.15.0",
]
